name: Run Test

on:
    push:
        paths:
            - data/**
            - project/**

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            
            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: 3.11
            
            - name: Install dependencies
              run: |
               python -m pip install --upgrade pip
               pip install -r ./project/requirements.txt
            
            - name: Run test
              run: |
               cd project
               chmod +x tests.sh
               tests.sh
